### ISSUE TITLE
Error SENDTXN_ERR

### ISSUE THREAD

**Issue by DaemonBSD** [ChainDropOrg/token-list#17]
Erros trying to send some SHM to my wallet on chain Sphinx 1.x.
URL: https://chaindrop.org/?chainid=8082&token=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
![image](https://user-images.githubusercontent.com/4450628/229388869-97cd0f80-9a9a-4876-a5fe-45fcc149fcd4.png)

**Comment by shubham-rathod1** [comment]
Shardeum Betanet RPC is little slow now, that's why some transactions are failing.
